# Generated by Django 5.1.7 on 2025-08-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='postagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='blog.post'),
        ),
    ]
